window.course = {
    topics: [{
            id: 1,
            title: "Integrity is everyone's responsibility",
            subtitle: "10 mins reading",
            desc: "Some quick example text to build on the card title and make up the bulk of the card's content. ",
            subtopics: [{
                    id: 1,
                    title: "Trust and confidence",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 2,
                    title: "What are Chief Executive Instructions?",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 3,
                    title: "Ethical decision making",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 4,
                    title: "Integrity in practice",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 5,
                    title: "Need to know",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
            ],
        },
        {
            id: 2,
            title: "Inclusion and diversity",
            subtitle: "10 mins reading",
            desc: "Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text.",
            subtopics: [{
                    id: 1,
                    title: "Being your true self",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 2,
                    title: "Inclusion and diversity in practice",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 3,
                    title: "Supporting inclusiveness and diversity",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 4,
                    title: "Know your biases",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 5,
                    title: "Turn allyship into action",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
            ],
        },
        {
            id: 3,
            title: "Safe and secure workplaces",
            subtitle: "10 mins reading",
            desc: "Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text",
            subtopics: [{
                    id: 1,
                    title: "Measures to maintian security",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 2,
                    title: "Staying safe",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 3,
                    title: "Subtopic 3",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 4,
                    title: "Subtopic 4",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 5,
                    title: "Subtopic 5",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
            ],
        },
        {
            id: 4,
            title: "Cybersecurity",
            subtitle: "10 mins reading",
            desc: "Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text",
            subtopics: [{
                    id: 1,
                    title: "Information security",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 2,
                    title: "Software security",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 3,
                    title: "Subtopic 3",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 4,
                    title: "Subtopic 4",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 5,
                    title: "Subtopic 5",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
            ],
        },
        {
            id: 5,
            title: "Privacy & Taxpayer confidentially",
            subtitle: "10 mins reading",
            desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
            subtopics: [{
                    id: 1,
                    title: "Taxation Administration Act 1953",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 2,
                    title: "Unauthorised access",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 3,
                    title: "Public interest disclosure",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 4,
                    title: "Subtopic 4",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 5,
                    title: "Subtopic 5",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
            ],
        },
        {
            id: 6,
            title: "Fraud & Corruption",
            subtitle: "10 mins reading",
            desc: "Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text",
            subtopics: [{
                    id: 1,
                    title: "What is fraud?",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 2,
                    title: "What is corruption?",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 3,
                    title: "Understanding your responsibilities",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 4,
                    title: "Reporting  fraud",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
                {
                    id: 5,
                    title: "Subtopic 5",
                    subtitle: "10 mins reading",
                    desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
                },
            ],
        },
    ],
}